name: Publish Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install "jupyterlab==3.6.3" "jupyter_server<2,>=1.6" jupyter_server_terminals
        python -m pip install hatchling hatch-nodejs-version hatch-jupyter-builder jupyter_packaging~=0.10 build pip-tools twine
        python -m pip install aiohttp requests
        cd jupyterlab-ai-assistant
        npm cache clean --force
        npm install
        
    - name: Build and package
      run: |
        cd jupyterlab-ai-assistant
        # Build TypeScript code and extension
        npm run build:prod
        
        # Build wheel
        python -m build
        
        # Run the custom command to copy assets to the right locations
        python setup.py copy_assets
        
        # Validate wheel contents
        python -m pip install dist/*.whl --force-reinstall
        jupyter labextension list
    
    # - name: Publish to TestPyPI
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     user: __token__
    #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
    #     repository_url: https://test.pypi.org/legacy/
    #     packages-dir: jupyterlab-ai-assistant/dist/
    #     skip-existing: true
    #
    # - name: Publish to PyPI
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     user: __token__
    #     password: ${{ secrets.PYPI_API_TOKEN }}
    #     packages-dir: jupyterlab-ai-assistant/dist/
    #     skip-existing: true 